// Статус-бар (Material Design): строка состояния.

import { Palette } from "std-widgets.slint";

export component StatusBar inherits Rectangle {
    in property <string> status: "";
    height: 30px;
    background: Palette.alternate-background;

    HorizontalLayout {
        padding-left: 16px;
        padding-right: 16px;
        cross-axis-alignment: center;
        Text {
            text: status;
            color: Palette.alternate-foreground;
            font-size: 12px;
            horizontal-stretch: 1;
            overflow: elide;
        }
    }
}
